# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lldutCSvxpaY8JCUTKjJ0UCYTLCd5X7i
"""

X = str(input("traffic signal"))
if X == "green":
  print("goo")
elif X == "yellow":
  print("wait")
else:
  print("stop")

x = str(input(":"))
for x in range(20):
  print(x)

x = int(input("1 to 10"))
i = 0
for x in range(i, x+1, 4):
  print(x)

x = int(input("age"))
if x >= 18:
  print("eligible for vote")
else:
  print("not eligible for vote")

x = int(input("positive or negative"))
if x < 0:
  print("negative")
else:
  print("positive")

x = int(input("number:"))
if x <= 9 :
  print("single digit")
elif x < 100:
  print("double digit")
elif x < 1000:
  print("trible digit")
else:
  print("four digit")

x = int(input("number"))
if x % 3 ==0:
  print("divisible by three")
else:
  print("not divisible by three")